# sesh configuration
# https://github.com/joshmedeski/sesh

[default_session]
startup_command = ""

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = ""

[[session]]
name = "config"
path = "~/.config"
