# Local tmux theme

# global colors
set -g @color_bg "default"
set -g @color_fg "#575279"
set -g @color_muted "#9893a5"
set -g @color_border "#d9d3cb"
set -g @color_red "#ef4444"
set -g @color_green "#6a9955"
set -g @color_blue "#569cd6"
set -g @color_yellow "#d19a00"
set -g @color_orange "#ea9d34"
set -g @color_rose "#b07d62"

# status left look and feel
set -g status-left-length 50
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@color_red},fg=#{@color_bg},bold]  #S },#{#[bg=#{@color_bg},fg=#{@color_green}]  #S }}"
set -ga status-left "#[bg=#{@color_bg},fg=#{@color_muted},none]│"
set -ga status-left "#[bg=#{@color_bg},fg=#{@color_orange}]  #{pane_current_command} "
set -ga status-left "#[bg=#{@color_bg},fg=#{@color_muted},none]│"
set -ga status-left "#[bg=#{@color_bg},fg=#{@color_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-left "#[bg=#{@color_bg},fg=#{@color_muted},none]#{?window_zoomed_flag,│,}"
set -ga status-left "#[bg=#{@color_bg},fg=#{@color_yellow}]#{?window_zoomed_flag,  zoom ,}"

# status right look and feel
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#{?#{e|>=:10,#{battery_percentage}},#{#[bg=#{@color_red},fg=#{@color_bg}]},#{#[bg=#{@color_bg},fg=#{@color_green}]}} #{battery_icon} #{battery_percentage} "
set -ga status-right "#[bg=#{@color_bg},fg=#{@color_muted}, none]│"

# tmux layout / look
set -g status-position bottom
set -g status-style "bg=#{@color_bg}"
set -g status-justify "absolute-centre"

setw -g pane-border-status top
setw -g pane-border-format ""
setw -g pane-active-border-style "fg=#{?client_prefix,#{@color_red},#{@color_orange}}"
setw -g pane-border-style "bg=#{@color_bg},fg=#{@color_border}"
setw -g pane-border-lines single

set -wg automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"

set -g window-status-format " #I: #W "
set -g window-status-style "bg=#{@color_bg},fg=#{@color_muted}"
set -g window-status-last-style "bg=#{@color_bg},fg=#{@color_rose}"
set -g window-status-activity-style "bg=#{@color_red},fg=#{@color_bg}"
set -g window-status-bell-style "bg=#{@color_red},fg=#{@color_bg},bold"
set -gF window-status-separator "#[bg=#{@color_bg},fg=#{@color_border}] "
set -g window-status-current-format "#[fg=#{@color_blue},bg=#{@color_bg}]#[fg=#{@color_bg},bg=#{@color_blue},bold] #I: #W #[fg=#{@color_blue},bg=#{@color_bg},nobold]"
set -g window-status-current-style "bg=#{@color_blue},fg=#{@color_bg},bold"
