[metadata]
name = "sesh"
description = "Session manager"
requirements = ["sesh"]

[source]
command = [
  "sesh list --i"
]
ansi = true

[preview]

command = "COLORTERM=truecolor CLICOLOR_FORCE=1 sesh preview '{strip_ansi|split: |last}'"
ansi = true

[keybindings]
enter = "actions:connect"
ctrl-d = ["actions:kill", "reload_source"]

[actions.connect]
description = "Connect to selected session"

command = "sesh connect '{strip_ansi|split: |last}'"
mode = "execute"

[actions.kill]
description = "Kill selected tmux session"
command = "tmux has-session -t '{strip_ansi|split: |last}' 2>/dev/null && tmux kill-session -t '{strip_ansi|split: |last}'"
mode = "fork"
