[metadata]
name = "sesh"
description = "Session manager"
requirements = ["sesh"]

[source]
command = [
  "sesh list --i"
]
ansi = true

[preview]

command = "COLORTERM=truecolor CLICOLOR_FORCE=1 sesh preview '{strip_ansi|split: |last}'"
ansi = true

[keybindings]
enter = "actions:connect"

[actions.connect]
description = "Connect to selected session"

command = "sesh connect '{strip_ansi|split: |last}'"
mode = "execute"