#!/usr/bin/env zsh
# sesh-smart-connect [query]

query="$*"

if [[ -n "$query" ]]; then
  matches=(${(f)"$(zoxide query --list "$query" 2>/dev/null)"})
  if (( ${#matches} == 1 )); then
    sesh connect "${matches[1]}"
    exit 0
  elif (( ${#matches} > 1 )); then
    selected=$(printf '%s\n' "${matches[@]}" | tv --ansi --preview-command "COLORTERM=truecolor sesh preview {}")
    [[ -n "$selected" ]] && sesh connect "$selected"
    exit 0
  fi
fi

selected=$(sesh list -i | tv --ansi --preview-command "COLORTERM=truecolor CLICOLOR_FORCE=1 sesh preview {2}")

if [[ -n "$selected" ]]; then
  # Dùng awk bốc phần tử cuối cùng để loại bỏ icon  trước khi connect
  clean_name=$(echo "$selected" | awk '{print $NF}')
  echo '$clean_name'
  sesh connect "$clean_name"
fi